# Generated by Django 3.2.16 on 2022-12-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipestags',
            name='unique_ingredient',
        ),
        migrations.AddConstraint(
            model_name='recipestags',
            constraint=models.UniqueConstraint(fields=('recipes', 'tags'), name='unique_tag'),
        ),
    ]
