# Generated by Django 3.2.16 on 2022-12-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221225_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default=1, help_text='Загрузите фото к рецепту', upload_to='recipes/images/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
